name: hello-world-launcher
on:
  schedule:
    - cron: "0 10 14 3 *"
  workflow_dispatch:
permissions:
  actions: write
env:
  DRY_RUN: false
  NAME: World
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Launch workflow"
        run: gh workflow run hello-world.yaml --ref main --field name="${{ env.NAME }}" --field dry_run=${{ env.DRY_RUN }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
